al:
  vacancies:
  - chamber: upper
    district: '5'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '11'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '12'
    vacant_until: 2026-01-01
ca:
  vacancies:
  - chamber: lower
    district: '63'
    vacant_until: 2025-08-26
dc:
  vacancies:
  - chamber: legislature
    district: Ward 8
    vacant_until: 2026-01-01
fl:
  vacancies:
  - chamber: lower
    district: '3'
    vacant_until: 2026-01-01
  - chamber: upper
    district: '15'
    vacant_until: 2026-01-01
  - chamber: upper
    district: '19'
    vacant_until: 2025-06-10
ga:
  vacancies:
  - chamber: upper
    district: '21'
    vacant_until: 2026-01-01
hi:
  vacancies:
  - chamber: lower
    district: '18'
    vacant_until: 2026-01-01
la:
  vacancies: []
ma:
  vacancies:
  - chamber: lower
    district: 3rd Bristol
    vacant_until: 2026-01-01
mi:
  vacancies:
  - chamber: upper
    district: 35
    vacant_until: 2026-01-01
mo:
  vacancies:
  - chamber: lower
    district: '95'
    vacant_until: 2026-01-01
nd:
  vacancies:
  - chamber: lower
    district: '26'
    vacant_until: 2026-01-01
nh:
  vacancies:
  - chamber: lower
    district: Strafford 12
    vacant_until: 2026-01-01
  - chamber: lower
    district: Rockingham 25
    vacant_until: 2026-01-01
ny:
  vacancies: []
ok:
  vacancies:
  - chamber: lower
    district: '71'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '74'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '97'
    vacant_until: 2025-09-09
or:
  vacancies:
  - chamber: lower
    district: '26'
    vacant_until: 2026-01-01
ri:
  vacancies:
  - chamber: upper
    district: '4'
    vacant_until: 2025-07-01
sd:
  vacancies:
  - chamber: upper
    district: '22'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '1'
    vacant_until: 2026-01-01
us:
  vacancies:
  - chamber: lower
    district: AZ-7
    vacant_until: 2026-01-01
  - chamber: lower
    district: TX-18
    vacant_until: 2026-01-01
  - chamber: lower
    district: VA-11
    vacant_until: 2026-01-01
wa:
  vacancies:
  - chamber: upper
    district: 5
    vacant_until: 2025-06-23
