al:
  vacancies:
  - chamber: upper
    district: '5'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '11'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '12'
    vacant_until: 2026-01-01
ca:
  vacancies:
  - chamber: lower
    district: '63'
    vacant_until: 2025-08-26
dc:
  vacancies:
  - chamber: legislature
    district: Ward 8
    vacant_until: 2026-01-01
fl:
  vacancies:
  - chamber: upper
    district: '15'
    vacant_until: 2026-01-01
ga:
  vacancies:
  - chamber: upper
    district: '21'
    vacant_until: 2026-01-01
hi:
  vacancies:
  - chamber: lower
    district: '18'
    vacant_until: 2026-01-01
la:
  vacancies: []
ks:
  vacancies:
  - chamber: lower
    district: 70
    vacant_until: 2026-01-01
  - chamber: lower
    district: 85
    vacant_until: 2026-01-01
mi:
  vacancies:
  - chamber: upper
    district: 35
    vacant_until: 2026-01-01
mn:
  vacancies:
  - chamber: lower
    district: '34B'
    vacant_until: 2026-09-17
mo:
  vacancies:
  - chamber: lower
    district: '95'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '160'
    vacant_until: 2026-01-01
mt:
  vacancies:
  - chamber: lower
    district: '75'
    vacant_until: 2026-01-01
ms:
  vacancies:
  - chamber: lower
    district: '26'
    vacant_until: 2026-01-01
  - chamber: upper
    district: '24'
    vacant_until: 2026-01-01
  - chamber: upper
    district: '26'
    vacant_until: 2026-01-01
nd:
  vacancies:
  - chamber: lower
    district: '25'
    vacant_until: 2026-01-01
nh:
  vacancies:
  - chamber: lower
    district: Rockingham 25
    vacant_until: 2026-01-01
  - chamber: lower
    district: Coos 5
    vacant_until: 2026-01-01
ny:
  vacancies: []
ri:
  vacancies:
  - chamber: upper
    district: '4'
    vacant_until: 2025-08-06
sd:
  vacancies:
  - chamber: upper
    district: '22'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '1'
    vacant_until: 2026-01-01
tx:
  vacancies:
  - chamber: upper
    district: 9
    vacant_until: 2025-11-05
us:
  vacancies:
  - chamber: lower
    district: AZ-7
    vacant_until: 2026-01-01
  - chamber: lower
    district: TX-18
    vacant_until: 2026-01-01
  - chamber: lower
    district: VA-11
    vacant_until: 2026-01-01
va:
  vacancies:
  - chamber: lower
    district: 33
    vacant_until: 2025-08-16
ut:
  vacancies:
  - chamber: lower
    district: 51
    vacant_until: 2026-07-30
