name: Lint YAML

on:
  push:
    branches:
      - main
    paths:
      - "data/**"
      - "settings.yml"
      - ".yamllint"
      - "poetry.lock"
      - "pyproject.toml"
      - ".github/workflows/lint-yaml.yml"
  pull_request:
    branches:
      - main
    paths:
      - "data/**"
      - "settings.yml"
      - ".yamllint"
      - "poetry.lock"
      - "pyproject.toml"
      - ".github/workflows/lint-yaml.yml"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c  # v46.0.5
      with:
        dir_names: 'true'
    - name: List all changed directories
      env:
        ALL_CHANGED_DIRS: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        for file in ${ALL_CHANGED_DIRS}; do
          echo "$file was changed"
        done
    # Python & dependency installation
    - uses: actions/checkout@v3
    - name: Yaml file linting
      run: |
        docker run --rm \
        -v $(pwd):/code \
        registry.gitlab.com/pipeline-components/yamllint:latest \
        -s .
    - name: setup Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: install Poetry
      uses: snok/install-poetry@v1.3.3
    - name: cache Poetry virtualenv
      uses: actions/cache@v3
      id: cache
      with:
        path: ~/.virtualenvs/
        key: poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          poetry-${{ hashFiles('**/poetry.lock') }}
    - name: set poetry config path
      run: poetry config virtualenvs.path ~/.virtualenvs
    - name: install dependencies
      run: poetry install --no-root
      # if: steps.cache.outputs.cache-hit != 'true'

    - name: lint people
      run: poetry run os-people lint
      env:
        OS_PEOPLE_DIRECTORY: ${{ env.GITHUB_WORKSPACE }}
    - name: lint committees
      run: poetry run os-committees lint
      env:
        OS_PEOPLE_DIRECTORY: ${{ env.GITHUB_WORKSPACE }}
